namespace newtype.generator;

/// <summary>
/// Source text for the [Alias] attribute that gets injected into user compilations.
/// </summary>
internal static class NewtypeAttributeSource
{
    private const string AttributeName = "newtypeAttribute";
    private const string AttributeNamespace = "newtype";
    public const string FullyQualifiedName = $"{AttributeNamespace}.{AttributeName}";
    public const string GenericAttributeName = "newtypeAttribute`1";

    public const string Source = """
                                 // <auto-generated/>
                                 #nullable enable

                                 namespace newtype
                                 {
                                     /// <summary>
                                     /// Controls which features the newtype generator emits.
                                     /// </summary>
                                     [global::System.Flags]
                                     internal enum NewtypeOptions
                                     {
                                         /// <summary>All features enabled (default).</summary>
                                         None                    = 0,
                                         /// <summary>Suppress the implicit conversion from T to the alias.</summary>
                                         NoImplicitWrap          = 1,
                                         /// <summary>Suppress the implicit conversion from the alias to T.</summary>
                                         NoImplicitUnwrap        = 2,
                                         /// <summary>Suppress forwarding constructors from T.</summary>
                                         NoConstructorForwarding = 4,
                                         /// <summary>Suppress both implicit conversions.</summary>
                                         NoImplicitConversions   = NoImplicitWrap | NoImplicitUnwrap,
                                         /// <summary>Suppress implicit conversions and constructor forwarding.</summary>
                                         Opaque                  = NoImplicitConversions | NoConstructorForwarding,
                                     }

                                     /// <summary>
                                     /// Marks a partial type as a type alias for the specified type.
                                     /// The source generator will generate implicit conversions, operator forwarding,
                                     /// and interface implementations to make this type behave like the aliased type
                                     /// while remaining a distinct type for compile-time type safety.
                                     /// </summary>
                                     /// <typeparam name="T">The type to alias.</typeparam>
                                     [global::System.AttributeUsage(global::System.AttributeTargets.Struct | global::System.AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
                                     [global::System.Diagnostics.Conditional("newtype_GENERATOR")]
                                     internal sealed class newtypeAttribute<T> : global::System.Attribute
                                     {
                                         /// <summary>
                                         /// Creates a new alias attribute for the specified type.
                                         /// </summary>
                                         public newtypeAttribute() { }

                                         /// <summary>Controls which features the generator emits.</summary>
                                         public NewtypeOptions Options { get; set; }

                                         /// <summary>
                                         /// Overrides the MethodImplOptions applied to generated members.
                                         /// Default is <see cref="global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining"/>.
                                         /// Set to <c>default</c> (0) to omit the attribute entirely.
                                         /// </summary>
                                         public global::System.Runtime.CompilerServices.MethodImplOptions MethodImpl { get; set; }
                                             = global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining;
                                     }

                                     /// <summary>
                                     /// Non-generic version for older C# versions or when generic attributes aren't supported.
                                     /// </summary>
                                     [global::System.AttributeUsage(global::System.AttributeTargets.Struct | global::System.AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
                                     [global::System.Diagnostics.Conditional("newtype_GENERATOR")]
                                     internal sealed class newtypeAttribute : global::System.Attribute
                                     {
                                         /// <summary>
                                         /// The type being aliased.
                                         /// </summary>
                                         public global::System.Type AliasedType { get; }

                                         /// <summary>
                                         /// Creates a new alias attribute for the specified type.
                                         /// </summary>
                                         /// <param name="aliasedType">The type to alias.</param>
                                         public newtypeAttribute(global::System.Type aliasedType)
                                         {
                                             AliasedType = aliasedType;
                                         }

                                         /// <summary>Controls which features the generator emits.</summary>
                                         public NewtypeOptions Options { get; set; }

                                         /// <summary>
                                         /// Overrides the MethodImplOptions applied to generated members.
                                         /// Default is <see cref="global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining"/>.
                                         /// Set to <c>default</c> (0) to omit the attribute entirely.
                                         /// </summary>
                                         public global::System.Runtime.CompilerServices.MethodImplOptions MethodImpl { get; set; }
                                             = global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining;
                                     }
                                 }
                                 """;
}