namespace newtype.generator;

/// <summary>
/// Source text for the [Alias] attribute that gets injected into user compilations.
/// </summary>
internal static class ConstraintAttributeSource
{
    public const string AttributeName = "newtypeValidationAttribute";

    public const string Source = """
                                 // <auto-generated/>
                                 #nullable enable

                                 /// <summary>
                                 /// Used to mark validation methods for aliased types that are called upon construction.
                                 /// </summary>
                                 namespace newtype
                                 {
                                     [global::System.AttributeUsage(global::System.AttributeTargets.Method, AllowMultiple = false, Inherited = false)]
                                     [global::System.Diagnostics.Conditional("newtype_GENERATOR")]
                                     internal sealed class newtypeValidationAttribute : global::System.Attribute
                                     {
                                         /// <summary>
                                         /// Creates a new validation attribute.
                                         /// </summary>
                                         public newtypeValidationAttribute() { }

                                         /// <summary>Whether the validation method should remain in release or be stripped.</summary>
                                         public bool IncludeInRelease { get; set; }
                                     }
                                 }
                                 """;
}