// <auto-generated/>
// This is an EXAMPLE of what the generator produces for:
//   [Alias<Vector3>]
//   public readonly partial struct Position;
//
// The actual generated file will be in obj/GeneratedFiles/ after building.

#nullable enable

using System;
using System.Runtime.CompilerServices;

public partial readonly struct Position : global::System.IEquatable<Position>, global::System.IComparable<Position>, global::System.IFormattable
{
    private readonly global::System.Numerics.Vector3 _value;

    /// <summary>Creates a new Position from a Vector3.</summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public Position(global::System.Numerics.Vector3 value) => _value = value;

    /// <summary>Gets the underlying value.</summary>
    public global::System.Numerics.Vector3 Value
    {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => _value;
    }

    /// <summary>Implicitly converts from Vector3 to Position.</summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static implicit operator Position(global::System.Numerics.Vector3 value) => new Position(value);

    /// <summary>Implicitly converts from Position to Vector3.</summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static implicit operator global::System.Numerics.Vector3(Position value) => value._value;

    // Binary operators (forwarded from Vector3)
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static Position operator +(Position left, Position right) => left._value + right._value;

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static Position operator -(Position left, Position right) => left._value - right._value;

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static Position operator *(Position left, Position right) => left._value * right._value;

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static Position operator /(Position left, Position right) => left._value / right._value;

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static Position operator *(Position left, global::System.Single right) => left._value * right;

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static Position operator *(global::System.Single left, Position right) => left * right._value;

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static Position operator /(Position left, global::System.Single right) => left._value / right;

    // Unary operators
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static Position operator -(Position value) => -value._value;

    // Equality
    /// <inheritdoc/>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public bool Equals(Position other) => _value.Equals(other._value);

    /// <inheritdoc/>
    public override bool Equals(object? obj) => obj is Position other && Equals(other);

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static bool operator ==(Position left, Position right) => left.Equals(right);

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static bool operator !=(Position left, Position right) => !left.Equals(right);

    /// <inheritdoc/>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public int CompareTo(Position other) => _value.CompareTo(other._value);

    #region Static Members

    /// <summary>Forwards Vector3.Zero.</summary>
    public static Position Zero
    {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => new Position(global::System.Numerics.Vector3.Zero);
    }

    /// <summary>Forwards Vector3.One.</summary>
    public static Position One
    {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => new Position(global::System.Numerics.Vector3.One);
    }

    /// <summary>Forwards Vector3.UnitX.</summary>
    public static Position UnitX
    {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => new Position(global::System.Numerics.Vector3.UnitX);
    }

    /// <summary>Forwards Vector3.UnitY.</summary>
    public static Position UnitY
    {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => new Position(global::System.Numerics.Vector3.UnitY);
    }

    /// <summary>Forwards Vector3.UnitZ.</summary>
    public static Position UnitZ
    {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => new Position(global::System.Numerics.Vector3.UnitZ);
    }

    #endregion

    #region Instance Members

    /// <summary>Forwards Vector3.X.</summary>
    public global::System.Single X
    {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => _value.X;
    }

    /// <summary>Forwards Vector3.Y.</summary>
    public global::System.Single Y
    {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => _value.Y;
    }

    /// <summary>Forwards Vector3.Z.</summary>
    public global::System.Single Z
    {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => _value.Z;
    }

    /// <summary>Forwards Vector3.Length.</summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public global::System.Single Length() => _value.Length();

    /// <summary>Forwards Vector3.LengthSquared.</summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public global::System.Single LengthSquared() => _value.LengthSquared();

    #endregion

    /// <inheritdoc/>
    public override string ToString() => _value.ToString();

    /// <inheritdoc/>
    public string ToString(string? format, IFormatProvider? formatProvider) => _value.ToString(format, formatProvider);

    /// <inheritdoc/>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public override int GetHashCode() => _value.GetHashCode();
}
