namespace TypeAlias.Generator;

/// <summary>
/// Source text for the [Alias] attribute that gets injected into user compilations.
/// </summary>
internal static class newtypeAttributeSource
{
    public const string AttributeName = "newtypeAttribute";
    public const string AttributeNamespace = "newtype";
    public const string FullyQualifiedName = $"{AttributeNamespace}.{AttributeName}";
    public const string GenericAttributeName = "newtypeAttribute`1";
    
    public const string Source = """
        // <auto-generated/>
        #nullable enable
        
        namespace TypeAlias
        {
            /// <summary>
            /// Marks a partial struct as a type alias for the specified type.
            /// The source generator will generate implicit conversions, operator forwarding,
            /// and interface implementations to make this type behave like the aliased type
            /// while remaining a distinct type for compile-time type safety.
            /// </summary>
            /// <typeparam name="T">The type to alias.</typeparam>
            [global::System.AttributeUsage(global::System.AttributeTargets.Struct, AllowMultiple = false, Inherited = false)]
            [global::System.Diagnostics.Conditional("TYPEALIAS_GENERATOR")]
            internal sealed class newtypeAttribute<T> : global::System.Attribute
                where T : struct
            {
                /// <summary>
                /// Creates a new alias attribute for the specified type.
                /// </summary>
                public newtypeAttribute() { }
            }
            
            /// <summary>
            /// Non-generic version for older C# versions or when generic attributes aren't supported.
            /// </summary>
            [global::System.AttributeUsage(global::System.AttributeTargets.Struct, AllowMultiple = false, Inherited = false)]
            [global::System.Diagnostics.Conditional("TYPEALIAS_GENERATOR")]
            internal sealed class newtypeAttribute : global::System.Attribute
            {
                /// <summary>
                /// The type being aliased.
                /// </summary>
                public global::System.Type AliasedType { get; }
                
                /// <summary>
                /// Creates a new alias attribute for the specified type.
                /// </summary>
                /// <param name="aliasedType">The type to alias.</param>
                public newtypeAttribute(global::System.Type aliasedType)
                {
                    AliasedType = aliasedType;
                }
            }
        }
        """;
}
